import 'package:chunky/chunky.dart';
import 'package:toxic/extensions/stream.dart';

/// Processes text into vector embeddings for semantic search and similarity analysis.
///
/// The Embedder class takes raw text, divides it into chunks, and then
/// generates vector embeddings for each chunk using the specified embed driver
/// and model. This is a key component in building semantic search capabilities
/// and enabling retrieval-augmented generation (RAG) systems.
class Embedder {
  /// The driver used to generate embeddings
  final Future<List<double>> Function(String content) embedder;

  /// The chunker used to divide text into manageable pieces
  final Chunker chunker;

  /// The amount of text overlap between chunks in characters
  final int overlap;

  /// Creates a new Embedder with the specified parameters.
  ///
  /// @param driver The embedding driver implementation to use
  /// @param chunker The chunking strategy to apply to input text
  /// @param model The embedding model identifier to use
  /// @param overlap The amount of text overlap between chunks (default: 500)
  Embedder({required this.embedder, required this.chunker, this.overlap = 500});

  /// Transforms a stream of raw text into a stream of embedded chunks.
  ///
  /// This method chunks the input text, processes each chunk in parallel
  /// (controlled by the semaphore buffer), and generates embeddings for each chunk.
  ///
  /// @param rawFeed The input stream of text
  /// @param semaphoreBuffer The maximum number of concurrent embedding operations (default: 4)
  /// @return A stream of chunks with their corresponding vector embeddings
  Stream<EmbeddedChunk> transform(
    Stream<String> rawFeed, {
    int semaphoreBuffer = 4,
  }) => chunker
      .transformWithOverlap(rawFeed, overlap: overlap)
      .semaphoreMap<EmbeddedChunk>(
        semaphoreBuffer,
        (i) async =>
            EmbeddedChunk(chunk: i, embedding: await embedder(i.content)),
      );
}

/// Represents a text chunk with its corresponding vector embedding.
///
/// EmbeddedChunk combines a text chunk with its vector representation
/// generated by an embedding model. This is the basic unit used for
/// semantic search and similarity operations in the system.
class EmbeddedChunk {
  /// The original text chunk
  final Chunk chunk;

  /// The vector embedding of the chunk content
  final List<double> embedding;

  /// Creates a new embedded chunk with the specified chunk and embedding.
  ///
  /// @param chunk The original text chunk
  /// @param embedding The vector embedding representing the chunk's semantic content
  EmbeddedChunk({required this.chunk, required this.embedding});
}
